-- 공통 부모 테이블 (계정 구분)
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(200),
    PHONE VARCHAR2(20),
    USER_TYPE VARCHAR2(10) CHECK (USER_TYPE IN ('OWNER', 'SITTER')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);





-- 시퀀스 생성
CREATE SEQUENCE USERS_SEQ
    START WITH 1          -- 시작 값
    INCREMENT BY 1        -- 증가 값
    NOCACHE               -- 캐시 사용 안 함
    NOCYCLE               -- 값이 최대값에 도달하면 오류 발생
    MINVALUE 1            -- 최소 값
    MAXVALUE 999999999999; -- 최대 값
    
 -- 트리거 생성
CREATE OR REPLACE TRIGGER USERS_BEFORE_INSERT
    BEFORE INSERT ON USERS
    FOR EACH ROW
BEGIN
    :NEW.USER_ID := USERS_SEQ.NEXTVAL;
END;

INSERT INTO USERS (EMAIL, PASSWORD, NAME, ADDRESS, PHONE, USER_TYPE)
VALUES ('owner@example.com', 'password123', 'aaa', 'deagu', '123-456-7890', 'OWNER');

INSERT INTO USERS (EMAIL, PASSWORD, NAME, ADDRESS, PHONE, USER_TYPE)
VALUES ('sitter@example.com', 'password456', 'bbb', 'seoul', '987-654-3210', 'SITTER');

INSERT INTO USERS (EMAIL, PASSWORD, NAME, ADDRESS, PHONE, USER_TYPE)
VALUES ('owner2@example.com', 'password789', 'ccc', 'busan', '555-666-7777', 'OWNER');

select * from users;

drop table users;
drop table owner_profile;
drop table SITTER_PROFILE;

-- 오너 추가 정보
CREATE TABLE OWNER_PROFILE (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    ADDRESS VARCHAR2(200),
    PHONE VARCHAR2(20),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 시터 추가 정보
CREATE TABLE SITTER_PROFILE (
    USER_ID NUMBER PRIMARY KEY,
    NAME  VARCHAR2(50),
    ADDRESS     VARCHAR2(200),
    PHONE       VARCHAR2(20),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);


SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'USERS_SEQ';

DROP TRIGGER USERS_BEFORE_INSERT;